\"from langchain.tools import tool\"  
\"\"  
\"@tool\"  
\"def book_hotel(customer_name: str, start_date: str, end_date: str) -> str:\"  
\"    \\\"\\\"\\\"\" >> tools.py && echo \"    Books a hotel room for a given customer and date range.\" >> tools.py && echo \"\" >> tools.py && echo \"    Args:\" >> tools.py && echo \"        customer_name: The full name of the customer.\" >> tools.py && echo \"        start_date: The check-in date in YYYY-MM-DD format.\" >> tools.py && echo \"        end_date: The check-out date in YYYY-MM-DD format.\" >> tools.py && echo \"\" >> tools.py && echo \"    Returns:\" >> tools.py && echo \"        A confirmation message with the booking details.\" >> tools.py && echo \"    \\\"\\\"\\\"\"  
\"    print(f\\\"Attempting to book hotel for {customer_name} from {start_date} to {end_date}\\\")\"  
\"    return f\\\"Success! A room has been booked for {customer_name} from {start_date} to {end_date}.\\\"\"  
\"\"  
\"@tool\"  
\"def schedule_appointment(patient_name: str, date: str, time: str) -> str:\"  
\"    \\\"\\\"\\\"\" >> tools.py && echo \"    Schedules a doctor's appointment for a given patient at a specific date and time.\" >> tools.py && echo \"\" >> tools.py && echo \"    Args:\" >> tools.py && echo \"        patient_name: The full name of the patient.\" >> tools.py && echo \"        date: The date of the appointment in YYYY-MM-DD format.\" >> tools.py && echo \"        time: The time of the appointment in HH:MM (24-hour) format.\" >> tools.py && echo \"\" >> tools.py && echo \"    Returns:\" >> tools.py && echo \"        A confirmation message with the appointment details.\" >> tools.py && echo \"    \\\"\\\"\\\"\"  
\"    print(f\\\"Attempting to schedule appointment for {patient_name} on {date} at {time}\\\")\"  
\"    return f\\\"Confirmed: An appointment is scheduled for {patient_name} on {date} at {time}.\\\"\"  
\"\"  
\"def get_tools():\"  
\"    return [book_hotel, schedule_appointment]\" 
